name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://yeshwanthdayananda.github.io
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Verify secrets
      run: |
        echo "Checking required secrets..."
        [[ -z "${{ secrets.FIREBASE_API_KEY }}" ]] && echo "❌ FIREBASE_API_KEY is missing" || echo "✅ FIREBASE_API_KEY is set"
        [[ -z "${{ secrets.FIREBASE_AUTH_DOMAIN }}" ]] && echo "❌ FIREBASE_AUTH_DOMAIN is missing" || echo "✅ FIREBASE_AUTH_DOMAIN is set"
        [[ -z "${{ secrets.FIREBASE_PROJECT_ID }}" ]] && echo "❌ FIREBASE_PROJECT_ID is missing" || echo "✅ FIREBASE_PROJECT_ID is set"
        [[ -z "${{ secrets.FIREBASE_STORAGE_BUCKET }}" ]] && echo "❌ FIREBASE_STORAGE_BUCKET is missing" || echo "✅ FIREBASE_STORAGE_BUCKET is set"
        [[ -z "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" ]] && echo "❌ FIREBASE_MESSAGING_SENDER_ID is missing" || echo "✅ FIREBASE_MESSAGING_SENDER_ID is set"
        [[ -z "${{ secrets.FIREBASE_APP_ID }}" ]] && echo "❌ FIREBASE_APP_ID is missing" || echo "✅ FIREBASE_APP_ID is set"
        [[ -z "${{ secrets.ADMIN_PASSWORD }}" ]] && echo "❌ ADMIN_PASSWORD is missing" || echo "✅ ADMIN_PASSWORD is set"
        
        # Fail if any secret is missing
        if [[ -z "${{ secrets.FIREBASE_API_KEY }}" ]] || \
           [[ -z "${{ secrets.FIREBASE_AUTH_DOMAIN }}" ]] || \
           [[ -z "${{ secrets.FIREBASE_PROJECT_ID }}" ]] || \
           [[ -z "${{ secrets.FIREBASE_STORAGE_BUCKET }}" ]] || \
           [[ -z "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" ]] || \
           [[ -z "${{ secrets.FIREBASE_APP_ID }}" ]] || \
           [[ -z "${{ secrets.ADMIN_PASSWORD }}" ]]; then
          echo "❌ Some secrets are missing. Please check GitHub repository settings."
          exit 1
        fi
        echo "✅ All secrets are properly set"

    - name: Create .env file
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      run: |
        echo "REACT_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
        echo "REACT_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
        echo "REACT_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
        echo "REACT_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
        echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
        echo "REACT_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
        echo "REACT_APP_ADMIN_PASSWORD=$ADMIN_PASSWORD" >> .env

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        CI: false

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './build'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2 